name: Build Images

on:
  pull_request:
  workflow_dispatch:

jobs:
  build-python-dev:
    name: build-python-dev
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        arch: [x86_64, aarch64]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '^1.13.1'

      - name: Setup apko
        run: |
          go install chainguard.dev/apko@latest

      - name: Build python-3.11-dev
        run: |
          apko build python-3.11-dev.yaml ghcr.io/defenseunicorns/leapfrogai/python-3.11-dev python-3.11-dev-${{ matrix.arch }}.tar --debug --arch ${{ matrix.arch }}

      - name: Upload to ghcr.io
        run: |
          docker load -i python-3.11-dev-${{ matrix.arch }}.tar
          docker image ls
          docker push -a
