name: Build Images

on:
  pull_request:
  push:
  workflow_dispatch:

jobs:
  build-python-dev:
    name: build-python-dev
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        arch: [x86_64, aarch64]

    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - uses: actions/setup-go@93397bea11091df50f3d7e59dc26a7711a8bcfbe # v2.1.5
        with:
          go-version-file: 'go.mod'
      - name: Setup QEMU
        uses: docker/setup-qemu-action@68827325e0b33c7199eb31dd4e31fbe9023e06e3 # v3.0.0
      - run: |
          make apko
          ./apko build ./python-3.11-dev.yaml ghcr.io/defenseunicorns/leapfrogai/python-3.11-dev-${{ matrix.arch }}.tar --debug --arch ${{ matrix.arch }}

      - name: Check SBOM Conformance
        run: |
          set -euxo pipefail
          if ! ls *.spdx.json; then
            echo "no SBOMs found!"
            exit 1
          fi
          for f in *.spdx.json; do
            echo ::group::sbom.json
            cat $f
            echo ::endgroup::
            docker run --rm -v $(pwd)/$f:/sbom.json cgr.dev/chainguard/ntia-conformance-checker -v --file /sbom.json
          done
