name: Build Images

on:
  pull_request:
  push:
  workflow_dispatch:

jobs:
  build-python-dev:
    name: build-python-dev
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        arch: [x86_64, aarch64]

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version: '^1.13.1' # The Go version to download (if necessary) and use.
      - run: |
          go install chainguard.dev/apko@latest
          apko build python-3.11-dev.yaml ghcr.io/defenseunicorns/leapfrogai/python-3.11-dev-${{ matrix.arch }} python-3.11-dev-${{ matrix.arch }}.tar --debug --arch ${{ matrix.arch }}
